language: python

python:
  - "3.7"

cache: pip

sudo: required
dist: bionic

services:
  - docker

env:
  global:
    - FAF_DB_VERSION="v96"

before_install:
  - git clone https://github.com/cleborys/faf-league-db.git faf-league-db
      && pushd faf-league-db
      &&./ci/bootstrap.sh
      && popd
  - docker exec -i faf-league-db mysql -uroot -pbanana faf-league -e "select * from league;"
  - ./ci/init-rabbitmq.sh
  - python -m pip install pipenv

install:
  - pipenv sync --dev
  - docker build --build-arg TRAVIS_TAG -t faf-league-service .

script:
  - scripts/run_tests_with_coverage.sh
  - sed -i.bak s#/code/#$(pwd)/#g .coverage

after_success:
  - coveralls
